services:
  # --- Base Services ---
  mongodb:
    image: mongo:7.0.8
    container_name: mongo_cc
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - ./.mongo_data:/data/db
    command: ["--wiredTigerCacheSizeGB", "0.25"] # Límite interno de Mongo para cache
    deploy:
      resources:
        limits:
          cpus: "0.50" # Máximo 50% de un núcleo de CPU
          memory: 512M # Máximo 512MB de RAM
        reservations:
          memory: 128M # Garantiza al menos 128MB
    profiles:
      - base
  compass:
    image: haohanyang/compass-web:latest
    container_name: compass_web_panel
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Conecta automáticamente al servicio de mongo de arriba
      - CW_MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASS}@mongodb:27017
      - CW_ENABLE_EDIT_CONNECTIONS=true
    depends_on:
      - mongodb
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
    profiles:
      - base
  redis:
    image: redis:7.2-alpine
    container_name: redis_cc
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
    profiles:
      - base
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight_cc
    ports:
      - "5540:5540"
    environment:
      # Configura la conexión automática apuntando al contenedor de arriba
      - REDIS_EXTERNAL_URL=redis://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 256M
    profiles:
      - base
  qdrant:
    image: qdrant/qdrant:v1.17.1
    container_name: qdrant_vector_db
    restart: always
    ports:
      - "6333:6333" # API REST y Web Dashboard
      - "6334:6334" # gRPC (por si lo necesitas más adelante)
    environment:
      - QDRANT__SERVICE__ENABLE_PROFILING=true
    volumes:
      - ./.qdrant_data:/qdrant/storage:z
    deploy:
      resources:
        limits:
          cpus: "0.50" # Máximo 50% de un núcleo de CPU
          memory: 512M # Máximo 512MB de RAM (ideal para tus colecciones de testing)
        reservations:
          memory: 128M # Garantiza al menos 128MB
    profiles:
      - base
  prefect-server:
    image: prefecthq/prefect:3-python3.13
    container_name: prefect_server
    command: prefect server start --host 0.0.0.0
    environment:
      - PREFECT_SERVER_API_HOST=0.0.0.0
      # Opcional: Desactivar telemetría si buscas máxima privacidad local
      - PREFECT_ANALYTICS_ENABLED=false
      - PREFECT_UI_API_URL=http://localhost:4200/api
    ports:
      - "4200:4200"
    volumes:
      - ./.prefect_data:/root/.prefect
    deploy:
      resources:
        limits:
          cpus: "0.50" # Máximo 50% de un núcleo de CPU
          memory: 512M # Máximo 512MB de RAM (ideal para tus colecciones de testing)
        reservations:
          memory: 128M # Garantiza al menos 128MB
    profiles:
      - base

  # --- Custom Services ---
  production_api:
    image: angeluz07/cc-production:0.0.1 # use local if exists
    build: # if doesnt, build it
      context: .
      dockerfile: ./services/production/Dockerfile
    container_name: production_api
    ports:
      - "8000:8000"
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - UVICORN_RELOAD=${UVICORN_RELOAD:-true}
      - REDIS_URI=redis://redis:6379
      - MONGODB_URI=${MONGODB_URI}
    volumes:
      - ./.data:/app/.data:z
      - ./services/production:/app:z
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 0.25G
        reservations:
          cpus: "0.5"
          memory: 0.25G
    profiles:
      - custom
  embedding_api:
    image: angeluz07/embedding:0.0.1 # use local if exists
    build: # if doesnt, build it
      context: .
      dockerfile: ./services/embedding/Dockerfile
    container_name: embedding_api
    ports:
      - "8001:8001"
    environment:
      - UVICORN_RELOAD=${UVICORN_RELOAD:-true}
    volumes:
      - ./services/embedding/.data:/app/.data:z
      - ./services/embedding:/app:z
    deploy:
      resources:
        limits:
          cpus: "6.0"
          memory: 1.5G
        reservations:
          cpus: "1"
          memory: 0.5G
    profiles:
      - custom
  download_api:
    image: angeluz07/cc-download:0.0.1 # use local if exists
    build: # if doesnt, build it
      context: .
      dockerfile: ./services/download/Dockerfile
    container_name: download_api
    ports:
      - "8002:8002"
    environment:
      - UVICORN_RELOAD=${UVICORN_RELOAD:-true}
      - PREFECT_API_URL=http://prefect-server:4200/api
    volumes:
      - ./.data:/app/.data:z
      - ./services/download:/app:z
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
        reservations:
          cpus: "0.5"
          memory: 256M
    profiles:
      - custom
  download_worker:
    image: angeluz07/cc-download:0.0.1 # use local if exists
    build: # if doesnt, build it
      context: .
      dockerfile: ./services/download/Dockerfile
    container_name: download_worker
    command: prefect flow serve workers.download:download --name "main" --limit 2
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - WEBHOOK_URI=${WEBHOOK_URI}
    volumes:
      - ./.data:/app/.data:z
      - ./services/download:/app:z
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 2G
        reservations:
          cpus: "1.0"
          memory: 1G
    profiles:
      - custom
  video_api:
    image: angeluz07/cc-video-build:0.0.1 # use local if exists
    build: # if doesnt, build it
      context: .
      dockerfile: ./services/video/Dockerfile
    container_name: video_api
    ports:
      - "8003:8003"
    environment:
      - UVICORN_RELOAD=${UVICORN_RELOAD:-true}
      - PREFECT_API_URL=http://prefect-server:4200/api
    volumes:
      - ./.data:/app/.data:z
      - ./services/video:/app:z
    deploy:
      resources:
        limits:
          cpus: "6" # still have, a cpu intensive task in this api
          memory: 1G
        reservations:
          cpus: "1"
          memory: 1G
    profiles:
      - custom
  video_worker:
    image: angeluz07/cc-video-build:0.0.1 # use local if exists
    build: # if doesnt, build it
      context: .
      dockerfile: ./services/video/Dockerfile
    container_name: video_worker
    command: prefect flow serve workers.video:video_build --name "main" --limit 2
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - WEBHOOK_URI=${WEBHOOK_URI}
    volumes:
      - ./.data:/app/.data:z
      - ./services/video:/app:z
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: 2G
        reservations:
          cpus: "1"
          memory: 1G
    profiles:
      - custom
  discovery_api:
    image: angeluz07/cc-discovery:0.0.1 # use local if exists
    build: # if doesnt, build it
      context: .
      dockerfile: ./services/discovery/Dockerfile
    container_name: discovery_api
    extra_hosts:
      - "localhost:host-gateway"
    ports:
      - "8004:8004"
    environment:
      - QDRANTDB_URI=${QDRANTDB_URI}
      - EMBEDDER_URI=${EMBEDDER_URI}
      - UVICORN_RELOAD=${UVICORN_RELOAD:-true}
      - PREFECT_API_URL=http://prefect-server:4200/api
    volumes:
      - ./.data:/app/.data:z
      - ./services/discovery:/app:z
    deploy:
      resources:
        limits:
          cpus: "2" # still have, a cpu intensive task in this api
          memory: 1G
        reservations:
          cpus: "1"
          memory: 1G
    depends_on:
      - embedding_api
    profiles:
      - custom
  discovery_worker:
    image: angeluz07/cc-discovery:0.0.1 # use local if exists
    build: # if doesnt, build it
      context: .
      dockerfile: ./services/discovery/Dockerfile
    container_name: discovery_worker
    command: prefect flow serve workers.discovery:discovery --name "main" --limit 2
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - QDRANTDB_URI=${QDRANTDB_URI}
      - EMBEDDER_URI=${EMBEDDER_URI}
      - UVICORN_RELOAD=${UVICORN_RELOAD:-true}
      - PREFECT_API_URL=http://prefect-server:4200/api
      - WEBHOOK_URI=${WEBHOOK_URI}
    volumes:
      - ./.data:/app/.data:z
      - ./services/discovery:/app:z
    deploy:
      resources:
        limits:
          cpus: "2" # still have, a cpu intensive task in this api
          memory: 1G
        reservations:
          cpus: "1"
          memory: 1G
    depends_on:
      - embedding_api
    profiles:
      - custom
  # neo4j:
  #   image: neo4j:5.18.0-community
  #   container_name: neo4j_graph_db
  #   restart: always
  #   ports:
  #     - "7474:7474"       # HTTP (Dashboard/Browser de Neo4j)
  #     - "7687:7687"       # Bolt (Protocolo para conectar desde Python/Node)
  #   environment:
  #     - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PASS}
  #     # Optimización de memoria interna para que quepa en los 512MB de Docker
  #     - NEO4J_server_memory_heap_initial__size=128m
  #     - NEO4J_server_memory_heap_max__size=256m
  #     - NEO4J_server_memory_pagecache_size=128m
  #   volumes:
  #     - ./.neo4j_data/data:/data
  #     - ./.neo4j_data/logs:/logs
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.50'     # Máximo 50% de un núcleo de CPU
  #         memory: 512M    # Máximo 512MB de RAM
  #       reservations:
  #         memory: 128M    # Garantiza al menos 128MB
